local function printStatus()
    local line = string.rep("═", 50)
    local padding = string.rep(" ", 18)

    print("")
    print(line)
    print("")
    print(padding .. "⚠️  ระบบถูกปิดใช้งาน")
    print("")
    print(padding .. "สาเหตุ:  กำลังอัพเดทระบบ")
    print("")
    print(padding .. "⏳  กรุณารอสักครู่...")
    print("")
    print(line)
    print("")
    print("Ruleless Enchantment · System Maintenance")
    print("")
end

printStatus()
